[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tiktok"
  to = "/.netlify/functions/tiktok"
  status = 200

  [[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

   [[redirects]]
  from = "/getip"
  to = "/.netlify/functions/getip"
  status = 200
  
  [[redirects]]
  from = "/owner/info"
  to = "/.netlify/functions/info"
  status = 200

  [[redirects]]
  from = "/owner/listip"
  to = "/.netlify/functions/ips"
  status = 200

  [[redirects]]
  from = "/ip"
  to = "/.netlify/functions/ip"
  status = 200
  
