[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tiktok"
  to = "/.netlify/functions/tiktok"
  status = 200

  [[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

   [[redirects]]
  from = "/getip"
  to = "/.netlify/functions/getip"
  status = 200
  
  [[redirects]]
  from = "/api/tebakkata"
  to = "/.netlify/functions/tebakkata"
  status = 200

  [[redirects]]
  from = "/api/igdl"
  to = "/.netlify/functions/igdl"
  status = 200

  [[redirects]]
  from = "/ip"
  to = "/.netlify/functions/ip"
  status = 200
  
